variables:
  DOCKER_USERNAME: tbd
  DOCKER_PASSWORD: tbd
  DOCKER_REPO: tbd

# Release the image to the docker repository, and creates appropriate tags.
release-latest:
  stage: release-master
  image: docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Tag and push based on branch (master is latest)
    - "docker build --pull -t $DOCKER_REPO/$CI_PROJECT_NAME:latest ."
    - "docker push $DOCKER_REPO/$CI_PROJECT_NAME:$latest"
  only:
    - master
      
# Release the image to the docker repository, and creates appropriate tags.
release-tag:
  stage: release-tag
  image: docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - "docker build --pull -t $DOCKER_REPO/$CI_PROJECT_NAME:CI_COMMIT_TAG ."
    - "docker push $DOCKER_REPO/$CI_PROJECT_NAME:$CI_COMMIT_TAG"
  only:
    - tags
    
stages:
  - release-master
  - release-tag